// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

/*  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE2q8p1loatHcLUbS-9y9i6I3evVsHEk8',
    appId: '1:621645718668:web:e01b32f08815cd95cac7a9',
    messagingSenderId: '621645718668',
    projectId: 'piscinamobile4',
    authDomain: 'piscinamobile4.firebaseapp.com',
    storageBucket: 'piscinamobile4.firebasestorage.app',
  );
*/

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAM7kQw-EHOTAPx_uUsYP7vWF8FrwYAlpw",
    authDomain: "piscinamobile4.firebaseapp.com",
    projectId: "piscinamobile4",
    storageBucket: "piscinamobile4.firebasestorage.app",
    messagingSenderId: "621645718668",
    appId: "1:621645718668:web:3e6bae3421731ef4cac7a9"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGah45_N3-8pSjvWypR-HFggRhiWh5sOQ',
    appId: '1:621645718668:android:c081621b0d1a7e4ecac7a9',
    messagingSenderId: '621645718668',
    projectId: 'piscinamobile4',
    storageBucket: 'piscinamobile4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2doE9G78aEgKocFfNxX31EzCMF7ceXA',
    appId: '1:621645718668:ios:63f672de79557cb0cac7a9',
    messagingSenderId: '621645718668',
    projectId: 'piscinamobile4',
    storageBucket: 'piscinamobile4.firebasestorage.app',
    androidClientId: '621645718668-k4r0e7uol4q28qlhnrph22eufv8mvvgv.apps.googleusercontent.com',
    iosClientId: '621645718668-1cf2fpa0e79cbbvuf7acc3269vo1mn6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.piscineMobile4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2doE9G78aEgKocFfNxX31EzCMF7ceXA',
    appId: '1:621645718668:ios:63f672de79557cb0cac7a9',
    messagingSenderId: '621645718668',
    projectId: 'piscinamobile4',
    storageBucket: 'piscinamobile4.firebasestorage.app',
    androidClientId: '621645718668-k4r0e7uol4q28qlhnrph22eufv8mvvgv.apps.googleusercontent.com',
    iosClientId: '621645718668-1cf2fpa0e79cbbvuf7acc3269vo1mn6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.piscineMobile4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE2q8p1loatHcLUbS-9y9i6I3evVsHEk8',
    appId: '1:621645718668:web:1e4c3176e9e36378cac7a9',
    messagingSenderId: '621645718668',
    projectId: 'piscinamobile4',
    authDomain: 'piscinamobile4.firebaseapp.com',
    storageBucket: 'piscinamobile4.firebasestorage.app',
  );

}